#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;

die "No XML ID given!" unless $ARGV[0];

my($cmd, $file, @result);
my $row = 0;
my $depth = 0;

$cmd = "grep -r 'xml:id=\"$ARGV[0]\"' xml/";
recurse($cmd);
if (@result == 0) {
  die "XML ID not found!";
}
my $base_file = $result[0][0];
foreach my $row (@result) {
  $row->[0] = $base_file;
  print join(' -> ', @$row);
  print "\n";
}

sub recurse {
  my $cmd = shift;
  my @lines = qx($cmd);
  print Dumper(@lines);
  if(@lines == 0) {
    $row++;
  }
  foreach my $line (@lines) {
    my $file = extract_filename($line);
    $result[$row][$depth] = $file;
    my $cmd = "grep 'href=\"$file\"' xml/*.xml | egrep -v \"(link|xml-stylesheet|xml-model)\"";
    $depth++;
    recurse($cmd);
  }
  $depth = 1;
}

sub extract_filename {
  my $line = shift;
  my @arr = split(':', $line);
  @arr = split('/', $arr[0]);
  chomp($arr[1]);
  return $arr[1];
}

